<?php
/** @var \SomethingDigital\Auction\Block\Form\Submit $block */
?>
<form class="form" action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>" method="post" id="auction-request-form" enctype="multipart/form-data" autocomplete="off" data-mage-init='{"validation": {}}'>
    <legend class="legend">
        <span><?= $block->escapeHtml(__('Submit an Auction item')) ?></span>
    </legend>
    <div class="field required">
        <label for="item_name" class="label"><span><?= $block->escapeHtml(__('Item Name')) ?></span></label>
        <div class="control">
            <input type="text" name="item_name" title="item_name" class="input-text" id="item_name" data-validate='{required:true}'>
        </div>
    </div>
    <div class="field">
        <label for="item_sku" class="label"><span><?= $block->escapeHtml(__('Item SKU')) ?></span></label>
        <div class="control">
            <input type="text" name="item_sku" title="item_sku" class="input-text" id="item_sku" data-validate='{required:true}'>
        </div>
    </div>
    <div class="field required">
        <label for="item_owner_email" class="label"><span><?= $block->escapeHtml(__('Contact Email')) ?></span></label>
        <div class="control">
            <input type="text" name="item_owner_email" title="item_owner_email" class="input-text" id="item_owner_email" data-validate='{required:true, validate-email:true}'>
        </div>
    </div>
    <div class="field required">
        <label for="item_base_price" class="label"><span><?= $block->escapeHtml(__('Base Price')) ?></span></label>
        <div class="control">
            <input type="text" name="item_base_price" title="item_base_price" class="input-text" id="item_base_price" data-validate='{required:true, validate-number:true}'>
        </div>
    </div>
    <input type="text" name="item_base_price" title="item_base_price" class="input-text" id="item_base_price" data-validate='{required:true, validate-number:true}'>

    <div class="actions-toolbar">
        <div class="primary">
            <button
                type="submit"
                class="action submit primary"
                title="Submit Auction Item">
                <span><?= $block->escapeHtml(__('Submit Auction Item')) ?></span>
            </button>
        </div>
    </div>
</form>

